"""Convert a grading report JSON to a formatted PDF.

Usage:
    python scripts/generate_report_pdf.py outbox/physics_question_paper_grading_report.json

Reads the grading report and produces a professional PDF in the same directory.

Requires: pip install fpdf2
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.logging.logger import get_logger

logger = get_logger(__name__)


def _sanitize(text: str) -> str:
    """Replace Unicode chars unsupported by built-in PDF fonts with ASCII."""
    return (
        text
        .replace("\u2014", "--")
        .replace("\u2013", "-")
        .replace("\u2018", "'")
        .replace("\u2019", "'")
        .replace("\u201c", '"')
        .replace("\u201d", '"')
        .replace("\u2026", "...")
        .replace("\u00b2", "^2")
        .replace("\u00b3", "^3")
        .replace("\u2022", "-")
        .replace("\u03a9", "Ohm")
        .replace("\u00d7", "x")
    )


def build_pdf(report: dict, output_path: Path, feedback: str | None = None) -> None:
    """Build a formatted PDF from a grading report dict.

    Args:
        report: Grading report dictionary.
        output_path: Where to write the PDF.
        feedback: Optional student-facing feedback text to append as a final section.
    """
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # --- Title bar ---
    pdf.set_fill_color(26, 26, 46)
    pdf.rect(0, 0, 210, 28, style="F")
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 28, "  Grading Report", align="L")
    pdf.ln(32)

    # --- Student & submission info ---
    source = report.get("source_path", report.get("source", ""))
    student_name = report.get("student_name", "")
    page_count = report.get("page_count", "")
    total_score = report.get("total_score", 0)
    max_score = report.get("max_score", report.get("total_max_score", 0))
    percentage = report.get("percentage")
    if percentage is None and max_score:
        percentage = round(total_score / max_score * 100, 1)
    flagged = report.get("flagged_for_review", [])
    questions = report.get("question_summaries", report.get("questions", []))
    n_questions = len(questions)

    if student_name:
        _info_row(pdf, "Student", student_name)
    _info_row(pdf, "Submission", Path(source).name if source else "N/A")
    if page_count:
        _info_row(pdf, "Pages", str(page_count))
    _info_row(pdf, "Questions", str(n_questions))
    pdf.ln(4)

    # --- Score card with visual bar ---
    _render_score_card(pdf, total_score, max_score, percentage)
    pdf.ln(6)

    if flagged:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(180, 100, 0)
        pdf.cell(
            0, 6,
            _sanitize(f"  Flagged for review: Q{', Q'.join(str(q) for q in flagged)}"),
            new_x="LMARGIN", new_y="NEXT",
        )
        pdf.ln(2)

    # --- Section divider ---
    _section_heading(pdf, "Question-wise Breakdown")

    # --- Question breakdown ---
    for q in sorted(questions, key=lambda x: x.get("question_number", 0)):
        _render_question(pdf, q)

    # --- Feedback section ---
    if feedback and feedback.strip():
        pdf.ln(6)
        _section_heading(pdf, "Student Feedback")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        # Wrap each paragraph, preserving blank-line breaks
        for para in feedback.strip().split("\n\n"):
            para = _sanitize(para.strip())
            if para:
                pdf.multi_cell(0, 6, para, new_x="LMARGIN", new_y="NEXT")
                pdf.ln(3)

    # --- Footer ---
    pdf.ln(8)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(
        0, 5,
        "Generated by Automated Assignment Grading System",
        new_x="LMARGIN", new_y="NEXT", align="C",
    )

    pdf.output(str(output_path))


def _info_row(pdf, label: str, value: str) -> None:
    """Print a label: value info row."""
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(28, 6, f"{label}:", new_x="END")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 6, _sanitize(value), new_x="LMARGIN", new_y="NEXT")


def _render_score_card(pdf, total_score, max_score, percentage) -> None:
    """Render a score card with a visual progress bar."""
    y = pdf.get_y()

    # Background card
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(220, 225, 230)
    pdf.rect(10, y, 190, 30, style="DF")

    # Score text
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(26, 26, 46)
    score_text = f"{total_score} / {max_score}"
    pdf.set_xy(15, y + 3)
    pdf.cell(60, 10, score_text)

    # Percentage
    if percentage is not None:
        pdf.set_font("Helvetica", "B", 14)
        if percentage >= 80:
            pdf.set_text_color(34, 139, 34)
        elif percentage >= 50:
            pdf.set_text_color(180, 120, 0)
        else:
            pdf.set_text_color(200, 50, 50)
        pdf.set_xy(150, y + 3)
        pdf.cell(45, 10, f"{percentage:.1f}%", align="R")

    # Progress bar
    bar_x = 15
    bar_y = y + 18
    bar_w = 180
    bar_h = 6
    fill_ratio = min(total_score / max_score, 1.0) if max_score else 0

    # Bar background
    pdf.set_fill_color(230, 230, 230)
    pdf.rect(bar_x, bar_y, bar_w, bar_h, style="F")

    # Bar fill
    if percentage is not None and percentage >= 80:
        pdf.set_fill_color(72, 187, 120)
    elif percentage is not None and percentage >= 50:
        pdf.set_fill_color(236, 201, 75)
    else:
        pdf.set_fill_color(245, 101, 101)
    pdf.rect(bar_x, bar_y, bar_w * fill_ratio, bar_h, style="F")

    pdf.set_y(y + 32)


def _section_heading(pdf, title: str) -> None:
    """Render a section heading with an underline."""
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(26, 26, 46)
    pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(26, 26, 46)
    pdf.line(10, pdf.get_y(), 80, pdf.get_y())
    pdf.ln(4)


def _render_question(pdf, q: dict) -> None:
    """Render one question block in the PDF."""
    q_num = q.get("question_number", "?")
    score = q.get("score", 0)
    max_score = q.get("max_score", 0)
    q_text = q.get("question_text", "")
    reasoning = q.get("reasoning", "")
    flagged = q.get("flagged_for_review", False)
    student_answer = q.get("student_answer", "")
    rubric_mapping = q.get("rubric_mapping", "")

    # Check if we need a new page
    if pdf.get_y() > 230:
        pdf.add_page()

    # --- Question header bar ---
    if flagged:
        pdf.set_fill_color(255, 248, 230)
        bar_color = (220, 180, 50)
    elif score >= max_score and max_score > 0:
        pdf.set_fill_color(235, 250, 235)
        bar_color = (72, 187, 120)
    elif score == 0 and max_score > 0:
        pdf.set_fill_color(255, 240, 240)
        bar_color = (220, 70, 70)
    else:
        pdf.set_fill_color(248, 248, 248)
        bar_color = (180, 140, 50)

    y_start = pdf.get_y()

    # Left accent bar
    pdf.set_fill_color(*bar_color)
    pdf.rect(10, y_start, 3, 10, style="F")

    # Header background
    if flagged:
        pdf.set_fill_color(255, 248, 230)
    elif score >= max_score and max_score > 0:
        pdf.set_fill_color(235, 250, 235)
    elif score == 0 and max_score > 0:
        pdf.set_fill_color(255, 240, 240)
    else:
        pdf.set_fill_color(248, 248, 248)
    pdf.rect(13, y_start, 187, 10, style="F")

    # Question title
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(26, 26, 46)
    title = f"Q{q_num}"
    if q_text:
        clean = re.sub(
            rf"^\s*Q(?:uestion|ues|n)?\s*{q_num}\s*[.\):\-]?\s*",
            "",
            q_text,
            flags=re.IGNORECASE,
        ).strip()
        title += f".  {clean[:75]}"
    pdf.set_xy(15, y_start)
    pdf.cell(145, 10, _sanitize(title), align="L")

    # Score badge
    pdf.set_font("Helvetica", "B", 11)
    if score >= max_score and max_score > 0:
        pdf.set_text_color(34, 139, 34)
    elif score == 0 and max_score > 0:
        pdf.set_text_color(200, 50, 50)
    else:
        pdf.set_text_color(180, 120, 0)

    badge = f"{score}/{max_score}"
    if flagged:
        badge += "  [REVIEW]"
    pdf.cell(40, 10, badge, align="R", new_x="LMARGIN", new_y="NEXT")

    # Content area with left indent
    x_indent = 16

    # Student answer
    if student_answer:
        pdf.set_x(x_indent)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, "STUDENT ANSWER", new_x="LMARGIN", new_y="NEXT")
        pdf.set_x(x_indent)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(50, 50, 50)
        answer_display = student_answer[:250]
        if len(student_answer) > 250:
            answer_display += "..."
        pdf.multi_cell(180, 4.5, _sanitize(answer_display),
                       new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    # Reasoning
    if reasoning and not reasoning.startswith("Evaluation failed"):
        pdf.set_x(x_indent)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, "EVALUATION", new_x="LMARGIN", new_y="NEXT")
        pdf.set_x(x_indent)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(180, 4.5, _sanitize(reasoning),
                       new_x="LMARGIN", new_y="NEXT")
    elif reasoning.startswith("Evaluation failed"):
        pdf.set_x(x_indent)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(200, 50, 50)
        pdf.multi_cell(180, 4.5,
                       "Could not evaluate -- flagged for teacher review.",
                       new_x="LMARGIN", new_y="NEXT")

    # Rubric mapping (compact)
    if rubric_mapping:
        pdf.ln(1)
        pdf.set_x(x_indent)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(130, 130, 160)
        pdf.cell(0, 5, "RUBRIC", new_x="LMARGIN", new_y="NEXT")
        pdf.set_x(x_indent)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(130, 130, 150)
        # Show first 2 lines of rubric
        rubric_lines = rubric_mapping.strip().split("\n")
        rubric_preview = " ".join(line.strip() for line in rubric_lines[:3])
        if len(rubric_lines) > 3:
            rubric_preview += "..."
        pdf.multi_cell(180, 4, _sanitize(rubric_preview[:200]),
                       new_x="LMARGIN", new_y="NEXT")

    # Separator
    pdf.ln(3)
    pdf.set_draw_color(230, 230, 230)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert grading report JSON to PDF"
    )
    parser.add_argument(
        "report_json", type=Path, help="Path to the grading report JSON"
    )
    parser.add_argument(
        "--output", "-o", type=Path, default=None,
        help="Output PDF path (default: same dir, same name with .pdf)",
    )
    args = parser.parse_args()

    if not args.report_json.exists():
        logger.error("Report file not found: %s", args.report_json)
        sys.exit(1)

    report = json.loads(args.report_json.read_text(encoding="utf-8"))
    logger.info("Loaded report: %s", args.report_json.name)

    if args.output:
        out_path = args.output
    else:
        out_path = args.report_json.with_suffix(".pdf")

    build_pdf(report, out_path)
    logger.info("PDF written: %s", out_path)
    print(f"PDF generated: {out_path}")


if __name__ == "__main__":
    main()
